ci: wip release pipeline

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,26 +9,38 @@ jobs:
     name: Prepare
     runs-on: ubuntu-latest
 
+    env:
+      TAG: ${{ github.event.release.tag_name }}
+
     outputs:
-      tag_name: ${{ steps.generate-tag-name.outputs.TAG_NAME }}
+      tag_name: ${{ steps.generate-tag-name.outputs.tag }}
+      latest: ${{ steps.set-latest.outputs.latest }}
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+    - name: Tag Follows SemVer
+      run: |
+        if [[ ! "${TAG}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-(alpha|rc)\.[0-9]+)?$ ]]; then
+          echo "Invalid SemVer tag: ${TAG}" >&2
+          exit 1
+        fi
 
     - name: Generate Tag Name
       id: generate-tag-name
       run: |
         # remove v prefix
-        TAG=${{ github.event.release.tag_name }}
-        TAG=${TAG#v}
+        IMAGE_TAG=${TAG#v}
 
-        echo ${{ github.event.release.tag_name }}' >> $GITHUB_OUTPUT
+        echo -n "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
 
     # only tag as latest if the release is set to latest
     - name: set tag as latest
-      if: "!github.event.release.prerelease"
-      run: echo -n 'true' >> $GITHUB_OUTPUT
+      # if: "!github.event.release.prerelease"
+      run: |
+        if [ "${{ github.event.release.prerelease }}" == "false" ]; then
+          echo -n 'latest=true' >> $GITHUB_OUTPUT
+        else
+          echo -n 'latest=false' >> $GITHUB_OUTPUT
+        fi
 
   publish:
     name: Build And Publish
